# Generated by Django 3.0.3 on 2020-02-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='emp_base/')),
            ],
        ),
    ]
